module.exports = Object.freeze({
    READ_CATEGORY: "read_category",
    CREATE_CATEGORY: "create_category",
    UPDATE_CATEGORY: "update_category",
    DELETE_CATEGORY: "delete_category",
    READ_BRAND: "read_brand",
    CREATE_BRAND: "create_brand",
    UPDATE_BRAND: "update_brand",
    DELETE_BRAND: "delete_brand",
    READ_CONSIGNMENT: "read_consignment",
    UPDATE_CONSIGNMENT: "update_consignment",
    READ_IMPORTED_ORDER: "read_imported_order",
    CREATE_IMPORTED_ORDER: "create_imported_order",
    UPDATE_IMPORTED_ORDER: "update_imported_order",
    DELETE_IMPORTED_ORDER: "delete_imported_order",
    READ_NOTIFICATION: "read_notification",
    UPDATE_NOTIFICATION: "update_notification",
    READ_EXPORT_ORDER: "read_export_order",
    CREATE_EXPORT_ORDER: "create_export_order",
    UPDATE_EXPORT_ORDER: "update_export_order",
    DELETE_EXPORT_ORDER: "delete_export_order",
    READ_PRODUCT: "read_product",
    CREATE_PRODUCT: "create_product",
    UPDATE_PRODUCT: "update_product",
    DELETE_PRODUCT: "delete_product",
    READ_RATE: "read_rate",
    CREATE_RATE: "create_rate",
    DELETE_RATE: "delete_rate",
    READ_STATISTIC: "read_statistic",
    READ_USER: "read_user",
    CREATE_USER: "create_user",
    UPDATE_USER: "update_user",
    DELETE_USER: "delete_user",
  });
  